apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-deployment

spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: fastapi-app
    spec:
      containers:
        - name: fastapi-app-container
          image: docker.io/aziz77/fastapi-app:fastapi-img
          ports:
          - containerPort: 80
          env:
            
            - name: POSTGRES_HOST
              value: postgres-service
            - name: DB_USER
              value: postgres
            - name: POSTGRES_PORT
              value: '5432'
            - name: DB_NAME
              value: fastapi_db
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD

  selector:
    matchLabels:
      component: fastapi-app