apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: docker.io/aziz77/fastapi-app:fastapi-img
        ports:
        - containerPort: 80
        env:
            
            - name: POSTGRES_HOST
              value: postgres-service
            - name: DB_USER
              value: postgres
            - name: POSTGRES_PORT
              value: '5432'
            - name: DB_NAME
              value: fastapi_db
            - name: PGPASSWORD
              value: system